spring:
  application:
    name: myAccountSalesService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://35.187.210.66:3306/myAccount?characterEncoding=utf-8&useSSl=false
    username: lin.mq
    password: cTnSFrgWhTvgcm

server:
  port: 8080
  servlet:
    context-path: /myAccountSalesService
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
# ===== Custom swagger configuration ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: MyAccountSalesService
  try-host: http://localhost:${server.port}
feign:
  myAccountSalesService-name: myAccountSalesService
  myAccountSalesService-url: http://localhost:8080/myAccountSalesService/

